### ISSUE TITLE
French Translation

### ISSUE THREAD

**Issue by guillaumecaruso** [SmitdCatchy/warcry-companion#38]
Hi ! I translated the application in french. 

 Thanks for making this great app ! As a newcomer to warcry it's so useful !

You'll find the translation json here : [https://justpaste.it/a96up](https://justpaste.it/a96up)

Don't hesitate to contact me if need be, I'll be happy to help with the translation again.

**Comment by SmitdCatchy** [comment]
Hi,

I would love to add the translation, but the file on the given link
contains mainly hungarian phrases.
Please send me the correct file and I will add it asap ;) You can also join
our facebook group if you want :)
https://www.facebook.com/groups/791866102144880/
Many thanks in advance.

Best regard,
András

**Comment by SmitdCatchy** [comment]
French translation has been added.
